#!/bin/bash

# ============================================
# BY:  Isaac Lehman
# RUN: sh directory-to-webp <your directory>
# ============================================

# function to convert an image to webp
# ARGS:
#   $1 = the file name (ex. ../my-img.png)
#   $2 = the quality (ex. 80)
convert_webp () {
   image_file_name=$1
   image_file_name_no_ext="${image_file_name%.*}"
   image_file_name_webp="${image_file_name_no_ext}.webp"

   conversion_quality=$2
   # Convert to webp (makes a copy at 80% quality)
   chmod +x cwebp
   ./cwebp -mt -quiet -q $conversion_quality $image_file_name -o $image_file_name_webp
}

# find all images (png/jpg/jpeg) and place their paths in a temporary file
find $1 -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.jpeg \) > img_files.txt

# make a webp copy of them
cat img_files.txt | while read line 
do
   convert_webp $line 70
   echo "Converting: $line"
done

# remove the temporary file
rm img_files.txt